#!/usr/bin/env python3
"""
generate_gitignore.py
Detect the project type in a given directory and generate an appropriate .gitignore file.

Usage:
    python generate_gitignore.py /path/to/project [--dry-run]
"""

import os
import sys
import argparse

# ─── Gitignore templates ────────────────────────────────────────────────────

TEMPLATES = {
    "node": """\
# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*
.npm
dist/
build/
.cache/
.parcel-cache/
.next/
out/
.nuxt/
.vuepress/dist/
.env
.env.local
.env.*.local
coverage/
*.tgz
""",
    "python": """\
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
.venv/
venv/
ENV/
env/
.env
*.log
*.pot
*.pyc
.pytest_cache/
.coverage
htmlcov/
""",
    "java": """\
# Java / Maven / Gradle
target/
*.class
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar
*.log
.mtj.tmp/
hs_err_pid*
replay_pid*
# Gradle
.gradle/
build/
# Maven
.mvn/
!**/src/main/**
!**/src/test/**
# IDE
.idea/
*.iml
*.iws
.classpath
.project
.settings/
""",
    "rust": """\
# Rust
/target/
Cargo.lock
**/*.rs.bk
*.pdb
""",
    "go": """\
# Go
/vendor/
/dist/
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
go.sum
""",
    "dotnet": """\
# .NET / C#
bin/
obj/
*.user
*.suo
*.userosscache
*.sln.docstates
.vs/
[Bb]uild/
[Dd]ist/
[Pp]ublish/
*.nupkg
*.snupkg
*.nuget.props
*.nuget.targets
project.lock.json
project.fragment.lock.json
artifacts/
""",
    "general": """\
# General
.DS_Store
Thumbs.db
ehthumbs.db
Desktop.ini
$RECYCLE.BIN/
*.log
*.tmp
*.swp
*.swo
*~
.env
.env.local
secrets.*
""",
}

# ─── Detection logic ─────────────────────────────────────────────────────────

DETECTION_RULES = [
    ("node",   ["package.json", "yarn.lock", "pnpm-lock.yaml", "package-lock.json"]),
    ("python", ["requirements.txt", "setup.py", "setup.cfg", "pyproject.toml", "Pipfile", "poetry.lock"]),
    ("java",   ["pom.xml", "build.gradle", "build.gradle.kts", "gradlew"]),
    ("rust",   ["Cargo.toml"]),
    ("go",     ["go.mod", "go.sum"]),
    ("dotnet", ["*.csproj", "*.sln", "*.fsproj", "*.vbproj"]),
]

def detect_project_type(project_dir: str) -> list[str]:
    """Return a list of detected project types (may be more than one)."""
    detected = []
    files = set(os.listdir(project_dir))

    for ptype, markers in DETECTION_RULES:
        for marker in markers:
            # Support simple glob-like wildcards (only *.ext pattern)
            if marker.startswith("*"):
                ext = marker[1:]
                if any(f.endswith(ext) for f in files):
                    detected.append(ptype)
                    break
            elif marker in files:
                detected.append(ptype)
                break

    return detected or ["general"]


def build_gitignore(types: list[str]) -> str:
    parts = []
    seen = set()
    for t in types:
        if t not in seen:
            parts.append(TEMPLATES.get(t, ""))
            seen.add(t)
    # Always append general ignores
    if "general" not in seen:
        parts.append(TEMPLATES["general"])
    return "\n".join(parts).strip() + "\n"


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Generate .gitignore for a project directory.")
    parser.add_argument("project_dir", help="Path to the project root directory")
    parser.add_argument("--dry-run", action="store_true", help="Print output instead of writing file")
    args = parser.parse_args()

    project_dir = os.path.abspath(args.project_dir)
    if not os.path.isdir(project_dir):
        print(f"❌ Directory not found: {project_dir}", file=sys.stderr)
        sys.exit(1)

    types = detect_project_type(project_dir)
    print(f"🔍 Detected project type(s): {', '.join(types)}")

    content = build_gitignore(types)
    gitignore_path = os.path.join(project_dir, ".gitignore")

    if args.dry_run:
        print(f"\n--- Preview of .gitignore ---\n{content}--- End ---")
    else:
        existing = ""
        if os.path.exists(gitignore_path):
            with open(gitignore_path, "r", encoding="utf-8") as f:
                existing = f.read()
            print(f"⚠️  Existing .gitignore found — appending new rules.")
            content = existing.rstrip() + "\n\n# Auto-generated by github-onboarding skill\n" + content

        with open(gitignore_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✅ .gitignore written to: {gitignore_path}")


if __name__ == "__main__":
    main()
